### ISSUE TITLE
No police menu + several bugs

### ISSUE THREAD

**Issue by xnooztvFR** [ErikMast3r/Exclusiv-Altis-Life-new#68]
- I can't open police menu (unrestrain etc..)
- I can't pickup money etc..

I hope it will have helped you, I can look for any bugs if you want.

**Comment by ErikMast3r** [comment]
_interactionKey = if (count (actionKeys "User10") isEqualTo 0) then {221} else {(actionKeys "User10") select 0};

this says, you have the key 221 for this by default. (It's not Windows-key, cause of conflicts with ACE)
On german keyboard it is the "app" key. I don't know the french one.
You can fix it, if you search for the key on the french keyboard or you can bind the user action 10 key in the controls

**Comment by ErikMast3r** [comment]
https://native-network.net/forum/thread/23-keyhandler-case-nummern/

This are the keys and numbers

**Comment by xnooztvFR** [comment]
Good, thanks :)

**Comment by ErikMast3r** [comment]
Everything is tested and works (maybe not in the 0.0.1.2 release but in my WIP version)
