### ISSUE TITLE
Mapwünsche 

### ISSUE THREAD

**Issue by Walker-Mo** [ErikMast3r/Exclusiv-Altis-Life-new#90]
- [x] Neue Häuser für Kavala
- [x] Werbetafeln
- [x] Zwei neue CP's
- [x] Rettungswache
- [X] Moderner Koma Checkpoint
- [x] Umbau der Map für Modded Server
- [x] Umwandlung KH zur RW und Verlegung zur Kavala Baustelle
- [x] Verlegung des Modded PHQ zur Position des KH
- [x] Umbau des ehem. PHQ zum Yachthafen 
- [x] Flughafen HQ für Polizei und Rettungsdienst
- [X] Aussenstelle für Pol und Rettd in Pyrgos (insg. nur 3 HQ's(Kavala,Flughafen,Pyrgos))

**Comment by ErikMast3r** [comment]
- [ ] Arbeitsamt Kavala
- [ ] Autohaus Kavala
- [ ] Möbelgeschäft (IKEA oder sowas eben)
- [ ] Platzierung der ganzen Überwachungskameras (Mod bei Wolf erfragen)
- [ ] Gerichtsgebäude
- [ ] Bauhof (für Baufirma)
- [ ] Sitz der Stadtwerke
- [ ] Kanzleien
- [ ] Busdepot und evtl. Busbahnhof
- [ ] Taxizentrale
- [ ] Poststelle
